spring:
  jmx:
     default-domain: pf
  datasource:
    name: ds
    url: jdbc:mysql://10.13.149.6:3306/fiscocc_pf?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Fiscocc@123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 20
    maxWait: 10000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mail:
    host: smtp.163.com
    port: 25
    username: fiscocc@163.com
    password: fiscocc123456
    nick: Fisco-cc
    protocol: smtp
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  redis:
    host: 10.13.149.10
    port: 6379
    password: Fiscocc123456
onbc:
  evidence:
    url: http://10.12.149.5:24451/fiscocc-onbc/evidence
logging:
  path: /var/logs/pf