server: 
  port: 8000
spring:
  profiles:
    #启动时采用的配置文件
    active: dev
  http: 
    encoding: 
      charset: UTF-8
      enable: true
      force: true
  mvc: 
    #出现错误直接抛出异常
    throw-exception-if-no-handler-found: true
    #不要为资源文件建立映射
  resources:
    add-mappings: false
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cn.mcsj.demo.entity
#请求上链次数
chain:
  count:
    limit: 10
  evidence:
    appId: IDA1EQRG
#数据库查询条数
select:
#定时检查线程不退出，查找前几天数据
  chainTime: 5
#每次sleep 30毫秒，控制异步速度
  internalSleepTime: 30
  count:
    limit: 200
#定时任务启动间隔
schedule:
  time: 0 0/1 * * * ?
#Thread配置
my: 
  corePoolSize: 500
  maxPoolSize: 1000
  queueCapacity: 500
  keepAlive: 60